server:
  port: 9080

spring:
  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/

  datasource:
#    url: jdbc:mysql://10.0.0.254:3306/heh_bald_pay?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: Qwe@as123
    url: jdbc:mysql://zhskg.net:60005/heh_bald_pay?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: Zhskg@2020Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: wiki.heh.bald.pay.service.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl