server:
  port: 9090

spring:
  application:
    name: baldpay-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

security:
  user:
    password: mpay

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

logging:
  file: ./log/mpay-config.log

