server:
  port: 9090

spring:
  application:
    name: bald-pay-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

#security:
#  user:
#    password: baldpay

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

logging:
  file: ./log/bald-pay-config.log

